module.exports = (app) => {
    app.use('/admin', require("../admin1/route"));
    app.use('/admin', require("./storeRouter"));
    app.use('/admin', require("./appRouter"));
    app.use('/admin', require("./teamRouter"));
    app.use('/admin', require("./testimonialRouter"));
    app.use('/admin', require("./aboutRouter"));
    app.use('/admin', require("./productRouter"));
    app.use('/admin', require("./faqRoute"));
    app.use('/admin', require("../order/route"));
    app.use('/admin', require("./blogRoute"));
    app.use('/admin', require("../Coupon/route"));
    app.use('/admin', require("../payment/route"));
    app.use('/admin', require("../category/routes"));
    app.use('/admin', require("../users/route"));
    app.use('/admin', require("../Artists/routes"));
    app.use('/admin', require("../Vacancy/routes"));
    app.use('/admin', require("../Refer-And-point/routes"));
    app.use('/admin', require("../Contact-us/route"));
    app.use('/admin', require("./productPackageRouter"));
    app.use('/admin', require("../newLetter/routes"));
    app.use('/admin', require("./galleryRouter"));
    app.use('/admin', require("./siteSettingRouter"));
    //   app.use(`${apiV1Prefix}/user`, require('./userRoutes'));
};
