module.exports = (app) => {
    app.use(require("../admin1/route"));
    app.use(require("./storeRouter"));
    app.use(require("./appRouter"));
    app.use(require("./teamRouter"));
    app.use(require("./testimonialRouter"));
    app.use(require("./aboutRouter"));
    app.use(require("./productRouter"));
    app.use(require("./faqRoute"));
    app.use(require("../order/route"));
    app.use(require("./blogRoute"));
    app.use(require("../Coupon/route"));
    app.use(require("../payment/route"));
    app.use(require("../category/routes"));
    app.use(require("../users/route"));
    app.use(require("../Artists/routes"));
    app.use(require("../Vacancy/routes"));
    app.use(require("../Refer-And-point/routes"));
    app.use(require("../Contact-us/route"));
    app.use(require("./productPackageRouter"));
    app.use(require("../newLetter/routes"));
    app.use(require("./galleryRouter"));
    app.use(require("./siteSettingRouter"));
    //   app.use(`${apiV1Prefix}/user`, require('./userRoutes'));
};
